import { createFileRoute } from "@tanstack/react-router";
import { Pool, type PoolClient } from "pg";

const ADMIN_EMAIL = "lacviet55@proton.me";
type Permission = "watch_party.view" | "watch_party.warn" | "watch_party.close";
type Actor = { id: string; email?: string; isMainAdmin: boolean; permissions: Set<string> };
let pool: Pool | undefined;
let schemaReady = false;
const schema = `
alter table public.watch_parties add column if not exists join_locked boolean not null default false;
create table if not exists public.staff_permissions (
  user_id uuid not null references auth.users(id) on delete cascade, permission text not null,
  granted_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  primary key(user_id,permission)
);
create table if not exists public.watch_party_warnings (
  id uuid primary key default gen_random_uuid(), party_id uuid not null references public.watch_parties(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  message text not null check(char_length(message) between 1 and 300), created_at timestamptz not null default now()
);
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key, actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null, target_type text not null, target_id text not null,
  details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);`;

function db() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) throw new Error("DATABASE_URL is required");
  return (pool ??= new Pool({ connectionString, ssl: { rejectUnauthorized: false }, max: 2 }));
}

async function ensureSchema() {
  if (schemaReady) return;
  await db().query(schema);
  schemaReady = true;
}

function json(data: unknown, status = 200) {
  return Response.json(data, { status, headers: { "cache-control": "no-store" } });
}

async function verifyActor(request: Request): Promise<Actor | null> {
  const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!token || !url || !key) return null;
  const response = await fetch(`${url}/auth/v1/user`, {
    headers: { apikey: key, authorization: `Bearer ${token}` },
  });
  if (!response.ok) return null;
  const user = (await response.json()) as {
    id?: string;
    email?: string;
    app_metadata?: { role?: string };
  };
  if (!user.id) return null;
  const isMainAdmin = user.email?.toLowerCase() === ADMIN_EMAIL;
  const isDeputy = user.app_metadata?.role === "deputy_admin";
  const permissions =
    !isMainAdmin && isDeputy
      ? new Set<string>(
          (
            await db().query<{ permission: string }>(
              `select permission from public.staff_permissions where user_id=$1`,
              [user.id],
            )
          ).rows.map((row) => row.permission),
        )
      : new Set<string>();
  return { id: user.id, email: user.email, isMainAdmin, permissions };
}

function can(actor: Actor, permission: Permission) {
  return actor.isMainAdmin || actor.permissions.has(permission);
}

async function listUsers() {
  const { rows } = await db().query(
    `select id, email, raw_user_meta_data->>'display_name' as display_name,
            case when lower(email)=$1 then 'admin'
                 when raw_app_meta_data->>'role'='deputy_admin' then 'deputy_admin'
                 else 'member' end as role,
            created_at, last_sign_in_at, banned_until
     from auth.users order by created_at desc limit 500`,
    [ADMIN_EMAIL],
  );
  return rows;
}

async function listParties() {
  const exists = await db().query(`select to_regclass('public.watch_parties') as name`);
  if (!exists.rows[0]?.name) return [];
  const { rows } = await db().query(`
    select p.id, p.code, p.name, p.host_id, u.email as host_email,
           p.closed, p.join_locked, p.created_at, p.updated_at,
           (select count(*)::int from public.watch_party_members m where m.party_id=p.id) as member_count,
           (select count(*)::int from public.watch_party_messages x where x.party_id=p.id) as message_count
    from public.watch_parties p
    left join auth.users u on u.id = p.host_id
    order by p.created_at desc limit 300
  `);
  return rows;
}

async function audit(
  client: PoolClient,
  actor: Actor,
  action: string,
  targetId: string,
  details: Record<string, unknown> = {},
) {
  await client.query(
    `insert into public.admin_audit_log(actor_id,action,target_type,target_id,details)
     values($1,$2,'watch_party',$3,$4::jsonb)`,
    [actor.id, action, targetId, JSON.stringify(details)],
  );
}

async function warnParty(actor: Actor, partyId: string, message: string) {
  const client = await db().connect();
  try {
    await client.query("begin");
    const party = await client.query(
      `select id from public.watch_parties where id=$1 and closed=false for update`,
      [partyId],
    );
    if (!party.rowCount) {
      await client.query("rollback");
      return json({ error: "Phòng không tồn tại hoặc đã đóng" }, 404);
    }
    const recent = await client.query(
      `select 1 from public.watch_party_warnings
       where party_id=$1 and created_at > now() - interval '10 seconds' limit 1`,
      [partyId],
    );
    if (recent.rowCount) {
      await client.query("rollback");
      return json({ error: "Mỗi phòng chỉ nhận một cảnh báo trong 10 giây" }, 429);
    }
    await client.query(
      `insert into public.watch_party_warnings(party_id,actor_id,message) values($1,$2,$3)`,
      [partyId, actor.id, message],
    );
    await audit(client, actor, "watch_party.warn", partyId, { message });
    await client.query("commit");
    return json({ ok: true });
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

async function closeParty(actor: Actor, partyId: string) {
  const client = await db().connect();
  try {
    await client.query("begin");
    const result = await client.query(
      `update public.watch_parties set closed=true, updated_at=now()
       where id=$1 and closed=false returning id`,
      [partyId],
    );
    if (!result.rowCount) {
      await client.query("rollback");
      return json({ error: "Phòng không tồn tại hoặc đã đóng" }, 404);
    }
    await audit(client, actor, "watch_party.close", partyId);
    await client.query("commit");
    return json({ ok: true });
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

async function handler(request: Request) {
  try {
    await ensureSchema();
    const actor = await verifyActor(request);
    if (!actor) return json({ error: "Forbidden" }, 403);
    if (request.method === "GET") {
      if (!can(actor, "watch_party.view"))
        return json({ error: "Thiếu quyền watch_party.view" }, 403);
      return json({
        users: actor.isMainAdmin ? await listUsers() : [],
        parties: await listParties(),
        permissions: actor.isMainAdmin
          ? ["watch_party.view", "watch_party.warn", "watch_party.close"]
          : [...actor.permissions],
        isMainAdmin: actor.isMainAdmin,
      });
    }

    const body = (await request.json()) as Record<string, unknown>;
    const action = String(body.action ?? "");
    if (action === "warnParty") {
      if (!can(actor, "watch_party.warn"))
        return json({ error: "Thiếu quyền watch_party.warn" }, 403);
      const partyId = String(body.id ?? "").trim();
      const message = String(body.message ?? "").trim();
      if (!partyId || message.length < 1 || message.length > 300) {
        return json({ error: "Cảnh báo phải có từ 1 đến 300 ký tự" }, 400);
      }
      return warnParty(actor, partyId, message);
    }
    if (action === "closeParty") {
      if (!can(actor, "watch_party.close"))
        return json({ error: "Thiếu quyền watch_party.close" }, 403);
      const partyId = String(body.id ?? "").trim();
      if (!partyId) return json({ error: "Thiếu phòng" }, 400);
      return closeParty(actor, partyId);
    }

    if (!actor.isMainAdmin)
      return json({ error: "Chỉ Admin chính được thực hiện thao tác này" }, 403);
    if (action === "createUser") {
      const email = String(body.email ?? "")
        .trim()
        .toLowerCase();
      const password = String(body.password ?? "");
      const displayName = String(body.displayName ?? "").trim();
      if (!email || password.length < 6)
        return json({ error: "Email hoặc mật khẩu không hợp lệ" }, 400);
      const response = await fetch(`${process.env.SUPABASE_URL}/auth/v1/signup`, {
        method: "POST",
        headers: {
          apikey: process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
          "content-type": "application/json",
        },
        body: JSON.stringify({
          email,
          password,
          data: { display_name: displayName || email.split("@")[0] },
        }),
      });
      const result = (await response.json()) as { msg?: string; message?: string };
      return response.ok
        ? json({ ok: true })
        : json(
            { error: result.msg || result.message || "Không tạo được người dùng" },
            response.status,
          );
    }
    if (action === "updateUser") {
      const id = String(body.id ?? "");
      const email = String(body.email ?? "")
        .trim()
        .toLowerCase();
      const displayName = String(body.displayName ?? "").trim();
      if (!id || !email) return json({ error: "Thiếu dữ liệu" }, 400);
      const target = await db().query(`select lower(email) as email from auth.users where id=$1`, [
        id,
      ]);
      if (target.rows[0]?.email === ADMIN_EMAIL)
        return json({ error: "Không thể thao tác với Admin chính" }, 403);
      if (email === ADMIN_EMAIL)
        return json({ error: "Email này dành riêng cho Admin chính" }, 400);
      await db().query(
        `update auth.users set email=$2, raw_user_meta_data=coalesce(raw_user_meta_data,'{}'::jsonb) || jsonb_build_object('display_name',$3), updated_at=now() where id=$1`,
        [id, email, displayName],
      );
      await db().query(`update public.profiles set display_name=$2, updated_at=now() where id=$1`, [
        id,
        displayName,
      ]);
      return json({ ok: true });
    }
    if (action === "deleteUser") {
      const id = String(body.id ?? "");
      const target = await db().query(`select lower(email) as email from auth.users where id=$1`, [
        id,
      ]);
      if (!id || id === actor.id || target.rows[0]?.email === ADMIN_EMAIL) {
        return json({ error: "Không thể thao tác với Admin chính" }, 403);
      }
      await db().query(`delete from auth.users where id=$1`, [id]);
      return json({ ok: true });
    }
    if (action === "setDeputy") {
      const id = String(body.id ?? "");
      const enabled = body.enabled === true;
      const target = await db().query(`select lower(email) as email from auth.users where id=$1`, [
        id,
      ]);
      if (!target.rowCount) return json({ error: "Không tìm thấy tài khoản" }, 404);
      if (target.rows[0].email === ADMIN_EMAIL)
        return json({ error: "Không thể thao tác với Admin chính" }, 403);
      const client = await db().connect();
      try {
        await client.query("begin");
        await client.query(
          enabled
            ? `update auth.users set raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb) || '{"role":"deputy_admin"}'::jsonb, updated_at=now() where id=$1`
            : `update auth.users set raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb) - 'role', updated_at=now() where id=$1`,
          [id],
        );
        if (enabled) {
          await client.query(
            `insert into public.staff_permissions(user_id,permission,granted_by)
             select $1,permission,$2 from unnest(array['watch_party.view','watch_party.warn','watch_party.close']) permission
             on conflict(user_id,permission) do update set granted_by=excluded.granted_by`,
            [id, actor.id],
          );
        } else {
          await client.query(`delete from public.staff_permissions where user_id=$1`, [id]);
        }
        await client.query("commit");
      } catch (error) {
        await client.query("rollback");
        throw error;
      } finally {
        client.release();
      }
      return json({ ok: true });
    }
    if (action === "assignParty") {
      const userId = String(body.userId ?? "");
      const partyId = String(body.partyId ?? "");
      if (!userId || !partyId) return json({ error: "Thiếu người dùng hoặc phòng" }, 400);
      const party = await db().query(
        `select id from public.watch_parties where id=$1 and closed=false`,
        [partyId],
      );
      const target = await db().query(`select id from auth.users where id=$1`, [userId]);
      if (!party.rowCount) return json({ error: "Phòng không tồn tại hoặc đã đóng" }, 404);
      if (!target.rowCount) return json({ error: "Người dùng không tồn tại" }, 404);
      await db().query(
        `insert into public.watch_party_members(party_id,user_id) values($1,$2) on conflict(party_id,user_id) do nothing`,
        [partyId, userId],
      );
      return json({ ok: true });
    }
    return json({ error: "Unknown action" }, 400);
  } catch (error) {
    console.error("[admin]", error);
    return json({ error: error instanceof Error ? error.message : "Server error" }, 500);
  }
}

export const Route = createFileRoute("/api/admin")({
  server: {
    handlers: { GET: ({ request }) => handler(request), POST: ({ request }) => handler(request) },
  },
});
