/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MeRouteImport } from './routes/me'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as BrowseIndexRouteImport } from './routes/browse.index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CCodeRouteImport } from './routes/c.$code'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as BrowseTypeValueRouteImport } from './routes/browse.$type.$value'
import { Route as ApiPublicVsmovStreamRouteImport } from './routes/api/public/vsmov-stream'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrowseTypeValueRoute = BrowseTypeValueRouteImport.update({
  id: '/browse/$type/$value',
  path: '/browse/$type/$value',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVsmovStreamRoute = ApiPublicVsmovStreamRouteImport.update({
  id: '/api/public/vsmov-stream',
  path: '/api/public/vsmov-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/c/$code': typeof CCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
  '/browse/$type/$value': typeof BrowseTypeValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/c/$code': typeof CCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/browse': typeof BrowseIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
  '/browse/$type/$value': typeof BrowseTypeValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/c/$code': typeof CCodeRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/browse/': typeof BrowseIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/vsmov-stream': typeof ApiPublicVsmovStreamRoute
  '/browse/$type/$value': typeof BrowseTypeValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favorites'
    | '/history'
    | '/latest'
    | '/mcp'
    | '/me'
    | '/search'
    | '/settings'
    | '/upcoming'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/c/$code'
    | '/collections/$id'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/browse/'
    | '/collections/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/vsmov-stream'
    | '/browse/$type/$value'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favorites'
    | '/history'
    | '/latest'
    | '/mcp'
    | '/me'
    | '/search'
    | '/settings'
    | '/upcoming'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/c/$code'
    | '/collections/$id'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/browse'
    | '/collections'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/vsmov-stream'
    | '/browse/$type/$value'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/favorites'
    | '/history'
    | '/latest'
    | '/mcp'
    | '/me'
    | '/search'
    | '/settings'
    | '/upcoming'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/c/$code'
    | '/collections/$id'
    | '/movie/$slug'
    | '/watch/$slug'
    | '/browse/'
    | '/collections/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/vsmov-stream'
    | '/browse/$type/$value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  LatestRoute: typeof LatestRoute
  McpRoute: typeof McpRoute
  MeRoute: typeof MeRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UpcomingRoute: typeof UpcomingRoute
  WatchlistRoute: typeof WatchlistRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CCodeRoute: typeof CCodeRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  MovieSlugRoute: typeof MovieSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicVsmovStreamRoute: typeof ApiPublicVsmovStreamRoute
  BrowseTypeValueRoute: typeof BrowseTypeValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$type/$value': {
      id: '/browse/$type/$value'
      path: '/browse/$type/$value'
      fullPath: '/browse/$type/$value'
      preLoaderRoute: typeof BrowseTypeValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vsmov-stream': {
      id: '/api/public/vsmov-stream'
      path: '/api/public/vsmov-stream'
      fullPath: '/api/public/vsmov-stream'
      preLoaderRoute: typeof ApiPublicVsmovStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  LatestRoute: LatestRoute,
  McpRoute: McpRoute,
  MeRoute: MeRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UpcomingRoute: UpcomingRoute,
  WatchlistRoute: WatchlistRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CCodeRoute: CCodeRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  MovieSlugRoute: MovieSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicVsmovStreamRoute: ApiPublicVsmovStreamRoute,
  BrowseTypeValueRoute: BrowseTypeValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
