alter table public.watch_parties
  add column if not exists join_locked boolean not null default false;

drop policy if exists "Authenticated can view open parties" on public.watch_parties;
drop policy if exists "Party members view parties" on public.watch_parties;
create policy "Party members view parties" on public.watch_parties
for select to authenticated using (
  host_id=auth.uid() or exists (
    select 1 from public.watch_party_members m
    where m.party_id=watch_parties.id and m.user_id=auth.uid()
  )
);

drop policy if exists "Authenticated can read party messages" on public.watch_party_messages;
drop policy if exists "Users can view messages in open parties" on public.watch_party_messages;
drop policy if exists "Party members view messages" on public.watch_party_messages;
create policy "Party members view messages" on public.watch_party_messages
for select to authenticated using (
  exists (
    select 1 from public.watch_parties p
    join public.watch_party_members m on m.party_id=p.id and m.user_id=auth.uid()
    where p.id=watch_party_messages.party_id
  )
);

drop policy if exists "Users can send their own messages" on public.watch_party_messages;
drop policy if exists "Users can send messages to open parties" on public.watch_party_messages;
drop policy if exists "Users can send messages when chat allowed" on public.watch_party_messages;
drop policy if exists "Party members send allowed messages" on public.watch_party_messages;
create policy "Party members send allowed messages" on public.watch_party_messages
for insert to authenticated with check (
  user_id=auth.uid() and exists (
    select 1 from public.watch_parties p
    join public.watch_party_members m on m.party_id=p.id and m.user_id=auth.uid()
    where p.id=watch_party_messages.party_id and p.closed=false and (p.chat_mode='all' or p.host_id=auth.uid())
  )
);

create table if not exists public.staff_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  permission text not null check (permission in ('watch_party.view', 'watch_party.warn', 'watch_party.close')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (user_id, permission)
);
alter table public.staff_permissions
  add column if not exists granted_by uuid references auth.users(id) on delete set null;
alter table public.staff_permissions drop constraint if exists staff_permissions_permission_check;
alter table public.staff_permissions add constraint staff_permissions_permission_check
  check (permission in ('watch_party.view', 'watch_party.warn', 'watch_party.close'));

revoke insert, update, delete on public.watch_parties, public.watch_party_messages, public.watch_party_members from authenticated;

create table if not exists public.watch_party_warnings (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references public.watch_parties(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  message text not null check (char_length(message) between 1 and 300),
  created_at timestamptz not null default now()
);
create index if not exists watch_party_warnings_rate_limit
  on public.watch_party_warnings (party_id, created_at desc);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_log_actor_created
  on public.admin_audit_log (actor_id, created_at desc);

alter table public.staff_permissions enable row level security;
alter table public.watch_party_warnings enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists "party members read warnings" on public.watch_party_warnings;
create policy "party members read warnings" on public.watch_party_warnings
for select to authenticated using (
  exists (
    select 1 from public.watch_parties p
    left join public.watch_party_members m on m.party_id=p.id and m.user_id=auth.uid()
    where p.id=watch_party_warnings.party_id and (p.host_id=auth.uid() or m.user_id=auth.uid())
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='watch_party_warnings'
  ) then
    alter publication supabase_realtime add table public.watch_party_warnings;
  end if;
end $$;

grant all on public.staff_permissions, public.watch_party_warnings, public.admin_audit_log to service_role;
